Geometry approximation example
topology-tool-kit/ttk-data pull request #111
Opened 2021-11-26 16:52 UTC by emmwel

Includes a simplified python script and .md file for the TTK Examples website

2021-12-06 12:55 UTC, julien-tierny requested changes
thanks a lot for the PR.
could you please address the few minor remarks I entered?
thanks!

2021-12-06 12:55 UTC, julien-tierny commented on python/geometryApproximation.py
> +SaveData('CameraNodes.vtp', tTKIcospheresFromPoints1)
I don't believe this output needs to be stored for this example.
(that would simplify the script)

2021-12-06 12:55 UTC, julien-tierny commented on python/geometryApproximation.py
> +tTKIcospheresFromPoints1 = TTKIcospheresFromPoints(Input=tTKIcosphereFromObject1)
this pipeline node can be removed (see comment below)

2021-12-06 12:55 UTC, julien-tierny commented on python/geometryApproximation.py
> +streamlinesvtp = XMLPolyDataReader(FileName=['/home/emma/ttk/ttk-source/ttk-data-emmwel/GroundWater.cdb/streamlines.vtp'])
I don't believe the streamlines need to be loaded in this srcipt.
(they are not used further down the script)

2021-12-06 12:55 UTC, julien-tierny commented on docs/geometryApproximation.md
> +This example loads two geometric structures: the streamlines of a section of ground water and its surrounding stone.
I don't believe the python script needs to load the streamlines (see my comments below)

2021-12-06 12:55 UTC, julien-tierny commented on python/geometryApproximation.py
> +stonevtp = XMLPolyDataReader(FileName=['/home/emma/ttk/ttk-source/ttk-data-emmwel/GroundWater.cdb/stone.vtp'])
thanks for changing from an absolute to a relative path!
(i.e. just `GroundWater.cdb/stone.vtp`)

2021-12-06 12:55 UTC, julien-tierny commented on docs/geometryApproximation.md
> + An approximation of the geometry is calculated from the images using [DepthImageBasedGeometryApproximation](https://topology-tool-kit.github.io/doc/html/classttkDepthImageBasedGeometryApproximation.
Threshold -› `Threshold`

2021-12-06 12:55 UTC, julien-tierny commented on docs/geometryApproximation.md
> +Giving the icosphere around the object to [IcospheresFromPoints](https://topology-tool-kit.github.io/doc/html/classttkIcospheresFromPoints.html) yields icospheres at the coordinates of the cameras.
I believe that part of the script can be removed.

2021-12-06 12:55 UTC, julien-tierny commented on docs/geometryApproximation.md
> +- [streamlines.vtp](https://github.com/topology-tool-kit/ttk-data/tree/dev/GroundWater.cdb/streamlines.vtp): a mesh of the streamlines of the ground water.
I'd suggest to remove that input as it is not used in the script

2021-12-06 12:55 UTC, julien-tierny commented on docs/geometryApproximation.md
> +- `CameraNodes.vtp`: the points representing the positions of the cameras used to take images of the geometry.
I'd suggest to remove that output

2021-12-21 07:25 UTC, julien-tierny commented
hi @emmwel 
this is a friendly reminder: if you could address my quick remarks, that'd be awesome.
thanks!

2021-12-21 11:54 UTC, emmwel commented
> hi @emmwel this is a friendly reminder: if you could address my quick remarks, that'd be awesome. thanks!

Hi sorry for the late fix, I did it now and hope I got everything :)

2021-12-22 09:53 UTC, julien-tierny commented
alright, looks good. thanks!

2021-12-22 09:53 UTC, merged

2021-12-22 09:53 UTC, julien-tierny commented
can you please PR ttk's source code to include pointers to this example in the corresponding Doxygen and ParaView documentations?
thanks!