Datasets, state files and scripts for DMS paper
topology-tool-kit/ttk-data pull request #128
Opened 2022-07-07 16:35 UTC by julesvidal

Dear Julien, 
This PR contains the state files, data, scripts and documentation for the experiments from the DMS paper.
Additionally, I modified the `run.py` script in `tests/`, to be able to specify a resolution factor from the commandline, in order to produce high-res pictures from pvsm files.
I'll prepare some screenshots of the paraview states for the website. 
Cheers,
Jules

2022-07-08 15:06 UTC, julien-tierny requested changes
thanks a lot jules!
that's great stuff!

could you please address the few remarks I entered in my review?
thanks!

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "name": "at.vti",
could you please insert these items at the right spot in the file?
(the entries are supposed to be in alphabetical order of their name).

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "acknowledgement": "",
"acknowledgement": "Roberto Alvarez Boto",

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "url": ""
please check mathieu's paper to get the URL to the right scivis contest: https://arxiv.org/pdf/2107.07789

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "acknowledgement": "",
"IEEE SciVis Contest 20xx"
xx to be determined by looking at mathieu's paper: https://arxiv.org/pdf/2107.07789

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "acknowledgement": "",
"acknowledgement": "AIM@Shape",

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "acknowledgement": "",
"acknowledgement": "AIM@Shape",

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "url": ""
"url": "https://github.com/topology-tool-kit/ttk-data"

2022-07-08 15:06 UTC, julien-tierny commented on README
> +  "acknowledgement": "",
"acknowledgement": "Jules Vidal",

2022-07-08 15:06 UTC, julien-tierny commented on docs/persistentGenerators_at.md
> +[PersistentGenerators](https://topology-tool-kit.github.io/doc/html/classttkPersistentGenerators.html)
can you please make sure that **all** the TTK modules used in the corresponding python script are indeed listed here? 
(I have the impression that a few mkdocs files for this PR are missing a few TTK modules).
also, can you make sure that the entries are listed in alphabetical order?

2022-07-08 15:06 UTC, julien-tierny commented on docs/persistentGenerators_householdAnalysis.md
> +This example shows the detection of a circular pattern in hiigh-dimensional data.
hiigh --> high

2022-07-08 15:06 UTC, julien-tierny commented on docs/persistentGenerators_periodicPicture.md
> +This example shows the detection of a circular pattern in hiigh-dimensional data.
hiigh -> high

2022-07-08 15:06 UTC, julien-tierny commented on docs/persistentGenerators_periodicPicture.md
> +
back to my previous comment, the TTK cinema filters are not referenced here.
(thanks for listing all the TTK modules used in the python script).

also, thanks for putting them in alphabetical order.

2022-07-08 15:06 UTC, julien-tierny commented on python/persistentGenerators_householdAnalysis.py
> +tTKRipsComplex1.SelectFieldswithaRegexp = 1
is the (long) specification of the input columns (below) required?
isn't the regexp sufficient?

in other words, does the script work if you remove the next line?

2022-07-08 15:06 UTC, julien-tierny commented on python/persistentGenerators_periodicPicture.py
> +tTKTableDistanceMatrix1.InputColumns = ['0000', '0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019',
cf my above remark:

"
is the (long) specification of the input columns (below) required?
isn't the regexp sufficient?

in other words, does the script work if you remove the next line?
"

2022-07-11 08:28 UTC, julesvidal commented
Hi Julien, 
I addressed your comments. 
Just a remark : the documentation links in multiple places to https://topology-tool-kit.github.io/doc/html/classttkPersistentGenerators.html, which is not created yet. Should I remove these links ?
cheers, 
jules

2022-07-11 08:30 UTC, julien-tierny commented
thanks a lot jules!
(and thanks for the heads up on the dead link: I'd suggest to keep things this way for the moment, I'll update the doxygen online documentation asap)

2022-07-11 08:32 UTC, julien-tierny commented
awesome, let's go!

2022-07-11 08:32 UTC, merged

2022-07-11 09:36 UTC, julien-tierny commented
One more thing: 
could you please go over the source code of **each module** used in each of these examples to insert (in the paraview xml file, the vtk header, the base class header, all in alphabetical order) the link to the corresponding example pages?

here are an example for the topological simplification:
- https://github.com/topology-tool-kit/ttk/blob/dev/paraview/xmls/TopologicalSimplification.xml
- https://github.com/topology-tool-kit/ttk/blob/dev/core/vtk/ttkTopologicalSimplification/ttkTopologicalSimplification.h
- https://github.com/topology-tool-kit/ttk/blob/dev/core/base/topologicalSimplification/TopologicalSimplification.h

thanks!