Document Morse-Smale Quadrangulation example
topology-tool-kit/ttk-data pull request #88
Opened 2021-11-25 15:09 UTC by pierre-guillou

This PR adds a simple Python script and a mkdocs file to document the ttk-data  MorseSmaleQuadrangulation state file. 

Enjoy,
Pierre

2021-11-26 06:17 UTC, julien-tierny commented
once your PR is merged, thanks for including a link to this example in the doxygen documentation of the involved modules.
see this commit for instance:
topology-tool-kit/ttk@2b9fd4c

2021-12-02 07:10 UTC, julien-tierny requested changes
thanks a lot pierre.
if you could address the few minor remarks I entered, that'd be wonderful.
thanks!

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +rockerArmvtu.PointArrayStatus = ["OutputEigenFunctions"]
I don't believe this line is necessary.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKPersistenceDiagram1.InputOffsetField = [None, ""]
I don't believe this line is necessary.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKTopologicalSimplification1.InputOffsetField = [None, ""]
I don't believe this line is necessary.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKTopologicalSimplification1.VertexIdentifierField = [None, ""]
I don't believe this line is necessary.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKMorseSmaleComplex1.OffsetField = ["POINTS", "Result"]
I don't believe this line is necessary.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tube1 = Tube(Input=extractSurface1)
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tube1.Scalars = ["POINTS", "CellDimension"]
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tube1.Vectors = [None, ""]
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tube1.Radius = 0.004
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +extractSurface1 = ExtractSurface(Input=tTKGeometrySmoother1)
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKGeometrySmoother1 = TTKGeometrySmoother(Input=OutputPort(tTKMorseSmaleComplex1, 1))
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKGeometrySmoother1.IterationNumber = 5
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKGeometrySmoother1.InputMaskField = [None, ""]
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKIcospheresFromPoints1.Radius = 0.01
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKIcospheresFromPoints1 = TTKIcospheresFromPoints(Input=tTKMorseSmaleComplex1)
pipeline dead leaf, please remove.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +    Triangulatedsurface=tTKIdentifierRandomizer1,
in principle, `OutputPort(tTKMorseSmaleComplex1, 3)` could be used instead here.
the randomizer is not really needed in this python script.

2021-12-02 07:10 UTC, julien-tierny commented on python/morseSmaleQuadrangulation.py
> +tTKIdentifierRandomizer1 = TTKIdentifierRandomizer(
to remove (see my comment below)

2021-12-02 07:10 UTC, julien-tierny commented on docs/morseSmaleQuadrangulation.md
> +disk. This mechanical model embeds a vector field with the output of
a vector field -› a collection of scalar fields
(usually, a vector field on a 2D surface is understood to have only 3 components, x y and z)

2021-12-02 10:12 UTC, pierre-guillou commented
Everything should be good now

2021-12-02 10:16 UTC, julien-tierny approved these changes

2021-12-02 10:16 UTC, julien-tierny commented
awesome, thanks!

2021-12-02 10:16 UTC, merged