Document Image Processing example
topology-tool-kit/ttk-data pull request #93
Opened 2021-11-25 16:39 UTC by pierre-guillou

This PR adds a simple Python script and a mkdocs file to document the ttk-data ImageProcessing state file.

Enjoy,
Pierre

2021-11-26 06:18 UTC, julien-tierny commented
once your PR is merged, thanks for including a link to this example in the doxygen and paraview documentation of the involved modules. see this commit for instance:
topology-tool-kit/ttk@2b9fd4c

2021-11-26 07:01 UTC, julien-tierny requested changes
thanks!
thanks for addressing the few remarks below.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +computeDerivatives1.Vectors = [None, ""]
I don't believe this line is necessary.
Thanks for double checking (e.g. with diff or paraview) that the outputs of the script are unchanged after the edit.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +tTKPersistenceDiagram1.InputOffsetField = [None, ""]
I don't believe this line is necessary.
Thanks for double checking (e.g. with diff or paraview) that the outputs of the script are unchanged after the edit.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +extractSurface2 = ExtractSurface(Input=threshold1)
dead leaf, please remove.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +tTKIcospheresFromPoints1 = TTKIcospheresFromPoints(Input=extractSurface1)
dead leaf, please remove.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +extractSurface1 = ExtractSurface(Input=persistenceThreshold)
dead leaf, please remove.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +tTKTopologicalSimplification1.InputOffsetField = [None, ""]
I don't believe this line is necessary.
Thanks for double checking (e.g. with diff or paraview) that the outputs of the script are unchanged after the edit.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +tTKTopologicalSimplification1.VertexIdentifierField = [None, ""]
I don't believe this line is necessary.
Thanks for double checking (e.g. with diff or paraview) that the outputs of the script are unchanged after the edit.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +tTKMorseSmaleComplex1.OffsetField = ["POINTS", "OutputOffsetScalarField"]
I don't believe this line is necessary.
Thanks for double checking (e.g. with diff or paraview) that the outputs of the script are unchanged after the edit.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +tube1 = Tube(Input=extractSurface3)
dead leaf, please remove.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +extractSurface3 = ExtractSurface(Input=threshold2)
dead leaf, please remove.

2021-11-26 07:01 UTC, julien-tierny commented on python/imageProcessing.py
> +threshold2.ThresholdRange = [-1.0, -0.1]
dead leaf, please remove

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +This example processes a black and white image (top left view on the
black and white -› greyscale

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +ParaView's ComputeDerivatives or Gradient filters. Since TTK only
ComputeDerivatives -› `ComputeDerivatives`

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +works on scalar field, a Calculator is used to compute the gradient
Calculator -› `Calculator`

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +filter. Since on the input image the objects correspond to low values
on the input image -› in the input image

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +the DescendingManifold scalar field of the Segmentation output, whose
DescendingManifold -› `DescendingManifold`

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +the DescendingManifold scalar field of the Segmentation output, whose
Segmentation -› `Segmentation`

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +filter is eventually used to ensure that neighboring cells are colored
to ensure (...) -› in order to color neighbor cells with a distinct color
(there is no guarantee)

2021-11-26 07:01 UTC, julien-tierny commented on docs/imageProcessing.md
> +  a black and white PNG image.
a greyscale PNG picture.

2021-11-26 10:00 UTC, pierre-guillou commented
Everything should be fixed/removed now

2021-12-02 07:48 UTC, julien-tierny approved these changes

2021-12-02 07:50 UTC, julien-tierny commented
awesome, thanks!

2021-12-02 07:50 UTC, merged